# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f63519172f6f79461a2f7a15999d4e55d7d81b3694f99c0d3561411ddcf259b094240c1d4e4159b08c50ca64246207e469a91d0297019d3eca1b3058a055aa47

test:
  secret_key_base: 693348b7994b84d4694c9ece0de550fbd42df7d5e258bdbe33257d6d4ee240f0422fe87e69009a097459a9f1d67b2bb3e606195551a8e708f3a0ccc626fbe6be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
